apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bloocube-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: IMAGE_URL
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: 0.0.0.0
            - name: NEXT_PUBLIC_API_URL
              value: "https://bloocube-backend-1027324977903.asia-southeast1.run.app"
      containerConcurrency: 80
      timeoutSeconds: 300
