substitutions:
  _REGION: asia-southeast1
  _SERVICE: bloocube-frontend
  _REPO: bloocube
  _IMAGE_TAG: latest
  _NEXT_PUBLIC_API_URL: https://api-backend.bloocube.com

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Optional: Faster builds
  
steps:
  # Step 1: Build container image with NEXT_PUBLIC_API_URL baked in
  - name: gcr.io/cloud-builders/docker
    id: 'build-image'
    args:
      - build
      - '-f'
      - 'Bloocube-frontend/Dockerfile'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$_IMAGE_TAG'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL'
      - 'Bloocube-frontend'

  # Step 2: Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: 'push-image'
    waitFor: ['build-image']
    args:
      - push
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$_IMAGE_TAG'

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: 'deploy-service'
    waitFor: ['push-image']
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '$_SERVICE'
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$_IMAGE_TAG'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--set-env-vars=NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL,NODE_ENV=production'

# Images to be pushed to registry
images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$_IMAGE_TAG'

# Timeout for entire build (increase if needed)
timeout: '1800s'